<a href="https://colab.research.google.com/github/skm08/transformers/blob/main/4_4_Models_and_Tokenizers_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from transformers import AutoTokenizer

In [ ]:
checkpoint = "bert-base-uncased"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
tokenizer

BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [ ]:
tokenizer("Hello World!")

{'input_ids': [101, 7592, 2088, 999, 102], 'token_type_ids': [0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1]}

In [ ]:
tokens = tokenizer.tokenize('Hello World!')

In [ ]:
tokens

['hello', 'world', '!']

In [ ]:
ids = tokenizer.convert_tokens_to_ids(tokens)

In [ ]:
ids

[7592, 2088, 999]

In [ ]:
tokenizer.convert_ids_to_tokens(ids)

['hello', 'world', '!']

In [ ]:
tokenizer.decode(ids)

'hello world!'

In [ ]:
ids = tokenizer.encode('Hello World!')

In [ ]:
ids

[101, 7592, 2088, 999, 102]

In [ ]:
tokenizer.convert_ids_to_tokens(ids)

['[CLS]', 'hello', 'world', '!', '[SEP]']

In [ ]:
tokenizer.decode(ids)

'[CLS] hello world! [SEP]'

In [ ]:
model_inputs = tokenizer('Hello World!')
model_inputs

{'input_ids': [101, 7592, 2088, 999, 102], 'token_type_ids': [0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1]}

In [ ]:
data = [
    "I like cats",
    "Do you like cats too?",
]
tokenizer(data)

{'input_ids': [[101, 1045, 2066, 8870, 102], [101, 2079, 2017, 2066, 8870, 2205, 1029, 102]], 'token_type_ids': [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}

In [ ]:
from transformers import AutoModelForSequenceClassification

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
# outputs = model(**model_inputs)

In [ ]:
model_inputs = tokenizer('Hello World!', return_tensors='pt')
model_inputs

{'input_ids': tensor([[ 101, 7592, 2088,  999,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}

In [ ]:
outputs = model(**model_inputs)

In [ ]:
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-0.2925, -0.0512]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    checkpoint, num_labels=3
)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-0.2997, -0.1203,  0.5366]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
outputs.logits

tensor([[-0.2997, -0.1203,  0.5366]], grad_fn=<AddmmBackward0>)

In [ ]:
outputs['logits']

tensor([[-0.2997, -0.1203,  0.5366]], grad_fn=<AddmmBackward0>)

In [ ]:
outputs[0]

tensor([[-0.2997, -0.1203,  0.5366]], grad_fn=<AddmmBackward0>)

In [ ]:
outputs.logits.detach().cpu().numpy()

array([[-0.2997148 , -0.12025508,  0.5366254 ]], dtype=float32)

In [ ]:
data = [
    "I like cats",
    "Do you like cats too?",
]
model_inputs = tokenizer(data,padding=True,truncation=True, return_tensors='pt')
model_inputs

{'input_ids': tensor([[ 101, 1045, 2066, 8870,  102,    0,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
model_inputs['input_ids']

tensor([[ 101, 1045, 2066, 8870,  102,    0,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]])

In [ ]:
model_inputs['attention_mask']

tensor([[1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-0.1736, -0.1522, -0.0308],
        [-0.3512, -0.1845,  0.5936]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

5. Transfer Learning & Fine-Tuning (pt 1)