<a href="https://www.kaggle.com/code/sagorkumarmitra/nlp-with-transformers-library-on-huggingface?scriptVersionId=222393984" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
!pip install transformers diffusers datasets evaluate accelerate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 3.0 MB/s eta 0:00:00


In [2]:
import transformers
import datasets
from datasets import load_dataset

In [3]:
reviews = load_dataset('rotten_tomatoes')

README.md:   0%|          | 0.00/7.46k [00:00<?, ?B/s]

train.parquet:   0%|          | 0.00/699k [00:00<?, ?B/s]

validation.parquet:   0%|          | 0.00/90.0k [00:00<?, ?B/s]

test.parquet:   0%|          | 0.00/92.2k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8530 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1066 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1066 [00:00<?, ? examples/s]

In [4]:
from huggingface_hub import notebook_login

In [5]:
notebook_login()

In [6]:
type(reviews)

datasets.dataset_dict.DatasetDict

In [7]:
reviews

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 8530
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 1066
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 1066
    })
})

In [8]:
help(reviews)

Help on DatasetDict in module datasets.dataset_dict object:

class DatasetDict(builtins.dict)
 |  A dictionary (dict of str: datasets.Dataset) with dataset transforms methods (map, filter, etc.)
 |  
 |  Method resolution order:
 |      DatasetDict
 |      builtins.dict
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __enter__(self)
 |  
 |  __exit__(self, exc_type, exc_val, exc_tb)
 |  
 |  __getitem__(self, k) -> datasets.arrow_dataset.Dataset
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  align_labels_with_mapping(self, label2id: Dict, label_column: str) -> 'DatasetDict'
 |      Align the dataset's label ID and label name mapping to match an input `label2id` mapping.
 |      This is useful when you want to ensure that a model's predicted labels are aligned with the dataset.
 |      The alignment in done using the lowercase label names.
 |      
 |      Args:
 |          label2id (`dict`):
 |              The label name 

In [9]:
reviews['train'].to_pandas()['text'][0]

'the rock is destined to be the 21st century\'s new " conan " and that he\'s going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .'

In [10]:
from transformers import pipeline

In [11]:
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cuda:0


In [12]:
classifier("This wasn't a great movie")

[{'label': 'NEGATIVE', 'score': 0.9997251629829407}]

In [13]:
test_df = reviews['test'].to_pandas()

In [14]:
test_df['text'][0]

'lovingly photographed in the manner of a golden book sprung to life , stuart little 2 manages sweetness largely without stickiness .'

In [15]:
def score(review_text):
    return classifier(review_text)[0]['label']

In [16]:
test_df['model_prediction'] = test_df['text'].apply(score)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset


In [17]:
test_df

text  label  \
0     lovingly photographed in the manner of a golde...      1   
1                 consistently clever and suspenseful .      1   
2     it's like a " big chill " reunion of the baade...      1   
3     the story gives ample opportunity for large-sc...      1   
4                     red dragon " never cuts corners .      1   
...                                                 ...    ...   
1061  a terrible movie that some people will neverth...      0   
1062  there are many definitions of 'time waster' bu...      0   
1063  as it stands , crocodile hunter has the hurrie...      0   
1064  the thing looks like a made-for-home-video qui...      0   
1065  enigma is well-made , but it's just too dry an...      0   

     model_prediction  
0            POSITIVE  
1            POSITIVE  
2            NEGATIVE  
3            POSITIVE  
4            POSITIVE  
...               ...  
1061         NEGATIVE  
1062         NEGATIVE  
1063         NEGATIVE  
1064         NEGATIVE  
1065         NEGATIVE  

[1066 rows x 3 columns]

In [18]:
from transformers import AutoModelForCausalLM, AutoTokenizer

In [19]:
gpt2 = AutoModelForCausalLM.from_pretrained("gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [20]:
tokenizer = AutoTokenizer.from_pretrained("gpt2")

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [21]:
sentence = "Hey! I'm a"

In [22]:
input_ids = tokenizer(sentence,return_tensors='pt').input_ids

In [23]:
input_ids

tensor([[10814,     0,   314,  1101,   257]])

In [24]:
tokenizer.decode(314)

' I'

In [25]:
gpt2 = AutoModelForCausalLM.from_pretrained("gpt2")

In [26]:
 input_ids

tensor([[10814,     0,   314,  1101,   257]])

In [27]:
output = gpt2(input_ids)

In [28]:
output.logits.shape

torch.Size([1, 5, 50257])

In [29]:
output.logits

tensor([[[ -36.0205,  -36.0670,  -39.6015,  ...,  -45.2210,  -44.6506,
           -37.3549],
         [-137.0499, -137.9498, -139.9256,  ..., -150.5155, -149.7149,
          -134.9536],
         [-151.9050, -153.2091, -157.5450,  ..., -163.8530, -156.8279,
          -155.6414],
         [-126.3497, -129.0852, -131.6853,  ..., -136.8222, -135.8820,
          -130.5265],
         [-102.7245, -103.3582, -105.4498,  ..., -111.7935, -110.2973,
          -104.7593]]], grad_fn=<UnsafeViewBackward0>)

In [30]:
final_logits = gpt2(input_ids).logits[0,-1]

In [31]:
final_logits

tensor([-102.7245, -103.3582, -105.4498,  ..., -111.7935, -110.2973,
        -104.7593], grad_fn=<SelectBackward0>)

In [32]:
final_logits.argmax()

tensor(1310)

In [33]:
tokenizer.decode(final_logits.argmax())

' little'

In [34]:
import torch

In [35]:
top10_logits = torch.topk(final_logits,10)

In [36]:
for index in top10_logits.indices:
    print(tokenizer.decode(index))

 little
 big
 bit
 fan
 girl
 real
 kid
 huge
 good
 guy


In [37]:
final_logits.softmax(dim=0)

tensor([5.6125e-05, 2.9782e-05, 3.6779e-06,  ..., 6.4648e-09, 2.8862e-08,
        7.3359e-06], grad_fn=<SoftmaxBackward0>)

In [38]:
top10 = torch.topk(final_logits.softmax(dim=0),10)

In [39]:
for value, index in zip(top10.values,top10.indices):
    print(f"{tokenizer.decode(index)} >> {value.item():.1%}")

 little >> 4.2%
 big >> 2.7%
 bit >> 1.7%
 fan >> 1.7%
 girl >> 1.1%
 real >> 1.0%
 kid >> 1.0%
 huge >> 0.8%
 good >> 0.8%
 guy >> 0.8%


In [40]:
input_ids

tensor([[10814,     0,   314,  1101,   257]])

In [41]:
output_ids = gpt2.generate(input_ids,max_new_tokens=20,repetition_penalty=1.5)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


In [42]:
output_ids[0]

tensor([10814,     0,   314,  1101,   257,  1310,  2739,   284,   262,  2151,
           11,   475,   345,   821,  7062,    13,   198,     1,    40,  1183,
          307,   736,  2582,   526,  1375])

In [43]:
decoded_text = tokenizer.decode(output_ids[0])

In [44]:
print(decoded_text)

Hey! I'm a little late to the party, but you're welcome.
"I'll be back soon." She


In [45]:
from transformers import pipeline

In [46]:
pipe = pipeline("text-generation",model="openai-community/gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cuda:0


In [47]:
pipe("I went to the book fair")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': "I went to the book fair in Brooklyn, and after the price drop it was like three hours. The publisher offered to sell me for $150, but I didn't really believe it. And then I did a book tour after that, so I"}]